// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/library.dart';
import 'api/player.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAppInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1919764982;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'musicplayer_ffi',
        ioDirectory: '../rust/ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiAppCoreVersion();

  List<String> crateApiAppDefaultAudioExtensions();

  Future<void> crateApiAppInitApp();

  Stats crateApiLibraryLibraryStats();

  List<Album> crateApiLibraryListAlbums();

  List<Artist> crateApiLibraryListArtists();

  List<Track> crateApiLibraryListTracks({
    required SortKey sort,
    required bool descending,
    int? limit,
  });

  void crateApiLibraryOpenLibrary({required String dbPath});

  void crateApiPlayerOpenPlayer();

  void crateApiPlayerPlayerNext();

  void crateApiPlayerPlayerPause();

  void crateApiPlayerPlayerPlay();

  void crateApiPlayerPlayerPrevious();

  void crateApiPlayerPlayerSeek({required int positionMs});

  void crateApiPlayerPlayerSetRepeat({required RepeatMode mode});

  PlayerSnapshot crateApiPlayerPlayerSnapshot();

  void crateApiPlayerPlayerStop();

  void crateApiPlayerPlayerToggle();

  Future<ScanSummary> crateApiLibraryScanLibrary({
    required List<String> roots,
    required ScanMode mode,
  });

  List<Track> crateApiLibrarySearchTracks({
    required String query,
    required int limit,
  });

  void crateApiPlayerSetPlayQueue({
    required List<QueueEntry> entries,
    required int startAt,
    required bool autoplay,
  });

  List<String> crateApiLibrarySuggestScanRoots();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiAppCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  List<String> crateApiAppDefaultAudioExtensions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppDefaultAudioExtensionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppDefaultAudioExtensionsConstMeta =>
      const TaskConstMeta(debugName: "default_audio_extensions", argNames: []);

  @override
  Future<void> crateApiAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stats crateApiLibraryLibraryStats() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stats,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryLibraryStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryLibraryStatsConstMeta =>
      const TaskConstMeta(debugName: "library_stats", argNames: []);

  @override
  List<Album> crateApiLibraryListAlbums() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_album,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryListAlbumsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListAlbumsConstMeta =>
      const TaskConstMeta(debugName: "list_albums", argNames: []);

  @override
  List<Artist> crateApiLibraryListArtists() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_artist,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryListArtistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListArtistsConstMeta =>
      const TaskConstMeta(debugName: "list_artists", argNames: []);

  @override
  List<Track> crateApiLibraryListTracks({
    required SortKey sort,
    required bool descending,
    int? limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_sort_key(sort, serializer);
          sse_encode_bool(descending, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryListTracksConstMeta,
        argValues: [sort, descending, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListTracksConstMeta => const TaskConstMeta(
    debugName: "list_tracks",
    argNames: ["sort", "descending", "limit"],
  );

  @override
  void crateApiLibraryOpenLibrary({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryOpenLibraryConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryOpenLibraryConstMeta =>
      const TaskConstMeta(debugName: "open_library", argNames: ["dbPath"]);

  @override
  void crateApiPlayerOpenPlayer() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerOpenPlayerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerOpenPlayerConstMeta =>
      const TaskConstMeta(debugName: "open_player", argNames: []);

  @override
  void crateApiPlayerPlayerNext() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerNextConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerNextConstMeta =>
      const TaskConstMeta(debugName: "player_next", argNames: []);

  @override
  void crateApiPlayerPlayerPause() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "player_pause", argNames: []);

  @override
  void crateApiPlayerPlayerPlay() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerPlayConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPlayConstMeta =>
      const TaskConstMeta(debugName: "player_play", argNames: []);

  @override
  void crateApiPlayerPlayerPrevious() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerPreviousConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerPreviousConstMeta =>
      const TaskConstMeta(debugName: "player_previous", argNames: []);

  @override
  void crateApiPlayerPlayerSeek({required int positionMs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_u_64(positionMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerSeekConstMeta,
        argValues: [positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSeekConstMeta =>
      const TaskConstMeta(debugName: "player_seek", argNames: ["positionMs"]);

  @override
  void crateApiPlayerPlayerSetRepeat({required RepeatMode mode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_repeat_mode(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerSetRepeatConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSetRepeatConstMeta =>
      const TaskConstMeta(debugName: "player_set_repeat", argNames: ["mode"]);

  @override
  PlayerSnapshot crateApiPlayerPlayerSnapshot() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_snapshot,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerSnapshotConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerSnapshotConstMeta =>
      const TaskConstMeta(debugName: "player_snapshot", argNames: []);

  @override
  void crateApiPlayerPlayerStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "player_stop", argNames: []);

  @override
  void crateApiPlayerPlayerToggle() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerToggleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerToggleConstMeta =>
      const TaskConstMeta(debugName: "player_toggle", argNames: []);

  @override
  Future<ScanSummary> crateApiLibraryScanLibrary({
    required List<String> roots,
    required ScanMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(roots, serializer);
          sse_encode_scan_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibraryScanLibraryConstMeta,
        argValues: [roots, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryScanLibraryConstMeta => const TaskConstMeta(
    debugName: "scan_library",
    argNames: ["roots", "mode"],
  );

  @override
  List<Track> crateApiLibrarySearchTracks({
    required String query,
    required int limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLibrarySearchTracksConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySearchTracksConstMeta =>
      const TaskConstMeta(
        debugName: "search_tracks",
        argNames: ["query", "limit"],
      );

  @override
  void crateApiPlayerSetPlayQueue({
    required List<QueueEntry> entries,
    required int startAt,
    required bool autoplay,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_queue_entry(entries, serializer);
          sse_encode_u_32(startAt, serializer);
          sse_encode_bool(autoplay, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetPlayQueueConstMeta,
        argValues: [entries, startAt, autoplay],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetPlayQueueConstMeta => const TaskConstMeta(
    debugName: "set_play_queue",
    argNames: ["entries", "startAt", "autoplay"],
  );

  @override
  List<String> crateApiLibrarySuggestScanRoots() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibrarySuggestScanRootsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySuggestScanRootsConstMeta =>
      const TaskConstMeta(debugName: "suggest_scan_roots", argNames: []);

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Album dco_decode_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Album(
      name: dco_decode_String(arr[0]),
      albumArtist: dco_decode_String(arr[1]),
      trackCount: dco_decode_u_32(arr[2]),
      durationMs: dco_decode_CastedPrimitive_u_64(arr[3]),
      year: dco_decode_opt_box_autoadd_u_32(arr[4]),
      hasCover: dco_decode_bool(arr[5]),
    );
  }

  @protected
  Artist dco_decode_artist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Artist(
      name: dco_decode_String(arr[0]),
      trackCount: dco_decode_u_32(arr[1]),
      albumCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Album> dco_decode_list_album(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_album).toList();
  }

  @protected
  List<Artist> dco_decode_list_artist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_artist).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<QueueEntry> dco_decode_list_queue_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_queue_entry).toList();
  }

  @protected
  List<Track> dco_decode_list_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  PlayerSnapshot dco_decode_player_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PlayerSnapshot(
      state: dco_decode_player_state(arr[0]),
      positionMs: dco_decode_CastedPrimitive_u_64(arr[1]),
      index: dco_decode_u_32(arr[2]),
      queueLen: dco_decode_u_32(arr[3]),
      trackId: dco_decode_CastedPrimitive_i_64(arr[4]),
      repeat: dco_decode_repeat_mode(arr[5]),
      error: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  PlayerState dco_decode_player_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerState.values[raw as int];
  }

  @protected
  QueueEntry dco_decode_queue_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return QueueEntry(
      id: dco_decode_CastedPrimitive_i_64(arr[0]),
      path: dco_decode_String(arr[1]),
    );
  }

  @protected
  RepeatMode dco_decode_repeat_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RepeatMode.values[raw as int];
  }

  @protected
  ScanMode dco_decode_scan_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ScanMode.values[raw as int];
  }

  @protected
  ScanSummary dco_decode_scan_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ScanSummary(
      added: dco_decode_u_32(arr[0]),
      updated: dco_decode_u_32(arr[1]),
      removed: dco_decode_u_32(arr[2]),
      skipped: dco_decode_u_32(arr[3]),
      failed: dco_decode_u_32(arr[4]),
      elapsedMs: dco_decode_CastedPrimitive_u_64(arr[5]),
      errors: dco_decode_list_String(arr[6]),
    );
  }

  @protected
  SortKey dco_decode_sort_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortKey.values[raw as int];
  }

  @protected
  Stats dco_decode_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Stats(
      trackCount: dco_decode_u_32(arr[0]),
      albumCount: dco_decode_u_32(arr[1]),
      artistCount: dco_decode_u_32(arr[2]),
      playlistCount: dco_decode_u_32(arr[3]),
      totalDurationMs: dco_decode_CastedPrimitive_u_64(arr[4]),
      totalSizeBytes: dco_decode_CastedPrimitive_u_64(arr[5]),
    );
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return Track(
      id: dco_decode_CastedPrimitive_i_64(arr[0]),
      path: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      artist: dco_decode_opt_String(arr[3]),
      album: dco_decode_opt_String(arr[4]),
      albumArtist: dco_decode_opt_String(arr[5]),
      genre: dco_decode_opt_String(arr[6]),
      year: dco_decode_opt_box_autoadd_u_32(arr[7]),
      trackNo: dco_decode_opt_box_autoadd_u_32(arr[8]),
      discNo: dco_decode_opt_box_autoadd_u_32(arr[9]),
      durationMs: dco_decode_CastedPrimitive_u_64(arr[10]),
      bitrate: dco_decode_opt_box_autoadd_u_32(arr[11]),
      sampleRate: dco_decode_opt_box_autoadd_u_32(arr[12]),
      channels: dco_decode_opt_box_autoadd_u_8(arr[13]),
      sizeBytes: dco_decode_CastedPrimitive_u_64(arr[14]),
      modifiedAt: dco_decode_CastedPrimitive_i_64(arr[15]),
      hasCover: dco_decode_bool(arr[16]),
      addedAt: dco_decode_CastedPrimitive_i_64(arr[17]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return inner.toInt();
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Album sse_decode_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_albumArtist = sse_decode_String(deserializer);
    var var_trackCount = sse_decode_u_32(deserializer);
    var var_durationMs = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_hasCover = sse_decode_bool(deserializer);
    return Album(
      name: var_name,
      albumArtist: var_albumArtist,
      trackCount: var_trackCount,
      durationMs: var_durationMs,
      year: var_year,
      hasCover: var_hasCover,
    );
  }

  @protected
  Artist sse_decode_artist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_trackCount = sse_decode_u_32(deserializer);
    var var_albumCount = sse_decode_u_32(deserializer);
    return Artist(
      name: var_name,
      trackCount: var_trackCount,
      albumCount: var_albumCount,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Album> sse_decode_list_album(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Album>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_album(deserializer));
    }
    return ans_;
  }

  @protected
  List<Artist> sse_decode_list_artist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Artist>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_artist(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<QueueEntry> sse_decode_list_queue_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <QueueEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_queue_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Track>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlayerSnapshot sse_decode_player_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_player_state(deserializer);
    var var_positionMs = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_index = sse_decode_u_32(deserializer);
    var var_queueLen = sse_decode_u_32(deserializer);
    var var_trackId = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_repeat = sse_decode_repeat_mode(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return PlayerSnapshot(
      state: var_state,
      positionMs: var_positionMs,
      index: var_index,
      queueLen: var_queueLen,
      trackId: var_trackId,
      repeat: var_repeat,
      error: var_error,
    );
  }

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayerState.values[inner];
  }

  @protected
  QueueEntry sse_decode_queue_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    return QueueEntry(id: var_id, path: var_path);
  }

  @protected
  RepeatMode sse_decode_repeat_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RepeatMode.values[inner];
  }

  @protected
  ScanMode sse_decode_scan_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ScanMode.values[inner];
  }

  @protected
  ScanSummary sse_decode_scan_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_added = sse_decode_u_32(deserializer);
    var var_updated = sse_decode_u_32(deserializer);
    var var_removed = sse_decode_u_32(deserializer);
    var var_skipped = sse_decode_u_32(deserializer);
    var var_failed = sse_decode_u_32(deserializer);
    var var_elapsedMs = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_errors = sse_decode_list_String(deserializer);
    return ScanSummary(
      added: var_added,
      updated: var_updated,
      removed: var_removed,
      skipped: var_skipped,
      failed: var_failed,
      elapsedMs: var_elapsedMs,
      errors: var_errors,
    );
  }

  @protected
  SortKey sse_decode_sort_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortKey.values[inner];
  }

  @protected
  Stats sse_decode_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_trackCount = sse_decode_u_32(deserializer);
    var var_albumCount = sse_decode_u_32(deserializer);
    var var_artistCount = sse_decode_u_32(deserializer);
    var var_playlistCount = sse_decode_u_32(deserializer);
    var var_totalDurationMs = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_totalSizeBytes = sse_decode_CastedPrimitive_u_64(deserializer);
    return Stats(
      trackCount: var_trackCount,
      albumCount: var_albumCount,
      artistCount: var_artistCount,
      playlistCount: var_playlistCount,
      totalDurationMs: var_totalDurationMs,
      totalSizeBytes: var_totalSizeBytes,
    );
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_albumArtist = sse_decode_opt_String(deserializer);
    var var_genre = sse_decode_opt_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_trackNo = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_discNo = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_durationMs = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_bitrate = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_sampleRate = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_channels = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_sizeBytes = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_modifiedAt = sse_decode_CastedPrimitive_i_64(deserializer);
    var var_hasCover = sse_decode_bool(deserializer);
    var var_addedAt = sse_decode_CastedPrimitive_i_64(deserializer);
    return Track(
      id: var_id,
      path: var_path,
      title: var_title,
      artist: var_artist,
      album: var_album,
      albumArtist: var_albumArtist,
      genre: var_genre,
      year: var_year,
      trackNo: var_trackNo,
      discNo: var_discNo,
      durationMs: var_durationMs,
      bitrate: var_bitrate,
      sampleRate: var_sampleRate,
      channels: var_channels,
      sizeBytes: var_sizeBytes,
      modifiedAt: var_modifiedAt,
      hasCover: var_hasCover,
      addedAt: var_addedAt,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(sseEncodeCastedPrimitiveI64(self), serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_album(Album self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.albumArtist, serializer);
    sse_encode_u_32(self.trackCount, serializer);
    sse_encode_CastedPrimitive_u_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_bool(self.hasCover, serializer);
  }

  @protected
  void sse_encode_artist(Artist self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.trackCount, serializer);
    sse_encode_u_32(self.albumCount, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_album(List<Album> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_album(item, serializer);
    }
  }

  @protected
  void sse_encode_list_artist(List<Artist> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_artist(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_queue_entry(
    List<QueueEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_queue_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_player_snapshot(
    PlayerSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_player_state(self.state, serializer);
    sse_encode_CastedPrimitive_u_64(self.positionMs, serializer);
    sse_encode_u_32(self.index, serializer);
    sse_encode_u_32(self.queueLen, serializer);
    sse_encode_CastedPrimitive_i_64(self.trackId, serializer);
    sse_encode_repeat_mode(self.repeat, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_queue_entry(QueueEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_i_64(self.id, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_repeat_mode(RepeatMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_scan_mode(ScanMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_scan_summary(ScanSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.added, serializer);
    sse_encode_u_32(self.updated, serializer);
    sse_encode_u_32(self.removed, serializer);
    sse_encode_u_32(self.skipped, serializer);
    sse_encode_u_32(self.failed, serializer);
    sse_encode_CastedPrimitive_u_64(self.elapsedMs, serializer);
    sse_encode_list_String(self.errors, serializer);
  }

  @protected
  void sse_encode_sort_key(SortKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_stats(Stats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.trackCount, serializer);
    sse_encode_u_32(self.albumCount, serializer);
    sse_encode_u_32(self.artistCount, serializer);
    sse_encode_u_32(self.playlistCount, serializer);
    sse_encode_CastedPrimitive_u_64(self.totalDurationMs, serializer);
    sse_encode_CastedPrimitive_u_64(self.totalSizeBytes, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_i_64(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.albumArtist, serializer);
    sse_encode_opt_String(self.genre, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackNo, serializer);
    sse_encode_opt_box_autoadd_u_32(self.discNo, serializer);
    sse_encode_CastedPrimitive_u_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitrate, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sampleRate, serializer);
    sse_encode_opt_box_autoadd_u_8(self.channels, serializer);
    sse_encode_CastedPrimitive_u_64(self.sizeBytes, serializer);
    sse_encode_CastedPrimitive_i_64(self.modifiedAt, serializer);
    sse_encode_bool(self.hasCover, serializer);
    sse_encode_CastedPrimitive_i_64(self.addedAt, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
