// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/app.dart';
import 'api/library.dart';
import 'api/playback_bridge.dart';
import 'api/player.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Album dco_decode_album(dynamic raw);

  @protected
  Artist dco_decode_artist(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CoverData dco_decode_box_autoadd_cover_data(dynamic raw);

  @protected
  Lyrics dco_decode_box_autoadd_lyrics(dynamic raw);

  @protected
  ResumePoint dco_decode_box_autoadd_resume_point(dynamic raw);

  @protected
  ResumeQueue dco_decode_box_autoadd_resume_queue(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  CoverData dco_decode_cover_data(dynamic raw);

  @protected
  DeleteSummary dco_decode_delete_summary(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_CastedPrimitive_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Album> dco_decode_list_album(dynamic raw);

  @protected
  List<Artist> dco_decode_list_artist(dynamic raw);

  @protected
  List<LyricLine> dco_decode_list_lyric_line(dynamic raw);

  @protected
  List<Playlist> dco_decode_list_playlist(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QueueEntry> dco_decode_list_queue_entry(dynamic raw);

  @protected
  List<QueueTrack> dco_decode_list_queue_track(dynamic raw);

  @protected
  List<Track> dco_decode_list_track(dynamic raw);

  @protected
  LyricLine dco_decode_lyric_line(dynamic raw);

  @protected
  Lyrics dco_decode_lyrics(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CoverData? dco_decode_opt_box_autoadd_cover_data(dynamic raw);

  @protected
  Lyrics? dco_decode_opt_box_autoadd_lyrics(dynamic raw);

  @protected
  ResumePoint? dco_decode_opt_box_autoadd_resume_point(dynamic raw);

  @protected
  ResumeQueue? dco_decode_opt_box_autoadd_resume_queue(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  PlayerSnapshot dco_decode_player_snapshot(dynamic raw);

  @protected
  PlayerState dco_decode_player_state(dynamic raw);

  @protected
  Playlist dco_decode_playlist(dynamic raw);

  @protected
  PlaylistFileFormat dco_decode_playlist_file_format(dynamic raw);

  @protected
  PlaylistImport dco_decode_playlist_import(dynamic raw);

  @protected
  QueueEntry dco_decode_queue_entry(dynamic raw);

  @protected
  QueueTrack dco_decode_queue_track(dynamic raw);

  @protected
  RepeatMode dco_decode_repeat_mode(dynamic raw);

  @protected
  ResumePoint dco_decode_resume_point(dynamic raw);

  @protected
  ResumeQueue dco_decode_resume_queue(dynamic raw);

  @protected
  ScanMode dco_decode_scan_mode(dynamic raw);

  @protected
  ScanSummary dco_decode_scan_summary(dynamic raw);

  @protected
  SortKey dco_decode_sort_key(dynamic raw);

  @protected
  Stats dco_decode_stats(dynamic raw);

  @protected
  Track dco_decode_track(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Album sse_decode_album(SseDeserializer deserializer);

  @protected
  Artist sse_decode_artist(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CoverData sse_decode_box_autoadd_cover_data(SseDeserializer deserializer);

  @protected
  Lyrics sse_decode_box_autoadd_lyrics(SseDeserializer deserializer);

  @protected
  ResumePoint sse_decode_box_autoadd_resume_point(SseDeserializer deserializer);

  @protected
  ResumeQueue sse_decode_box_autoadd_resume_queue(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  CoverData sse_decode_cover_data(SseDeserializer deserializer);

  @protected
  DeleteSummary sse_decode_delete_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Album> sse_decode_list_album(SseDeserializer deserializer);

  @protected
  List<Artist> sse_decode_list_artist(SseDeserializer deserializer);

  @protected
  List<LyricLine> sse_decode_list_lyric_line(SseDeserializer deserializer);

  @protected
  List<Playlist> sse_decode_list_playlist(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QueueEntry> sse_decode_list_queue_entry(SseDeserializer deserializer);

  @protected
  List<QueueTrack> sse_decode_list_queue_track(SseDeserializer deserializer);

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer);

  @protected
  LyricLine sse_decode_lyric_line(SseDeserializer deserializer);

  @protected
  Lyrics sse_decode_lyrics(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CoverData? sse_decode_opt_box_autoadd_cover_data(
    SseDeserializer deserializer,
  );

  @protected
  Lyrics? sse_decode_opt_box_autoadd_lyrics(SseDeserializer deserializer);

  @protected
  ResumePoint? sse_decode_opt_box_autoadd_resume_point(
    SseDeserializer deserializer,
  );

  @protected
  ResumeQueue? sse_decode_opt_box_autoadd_resume_queue(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  PlayerSnapshot sse_decode_player_snapshot(SseDeserializer deserializer);

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer);

  @protected
  Playlist sse_decode_playlist(SseDeserializer deserializer);

  @protected
  PlaylistFileFormat sse_decode_playlist_file_format(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistImport sse_decode_playlist_import(SseDeserializer deserializer);

  @protected
  QueueEntry sse_decode_queue_entry(SseDeserializer deserializer);

  @protected
  QueueTrack sse_decode_queue_track(SseDeserializer deserializer);

  @protected
  RepeatMode sse_decode_repeat_mode(SseDeserializer deserializer);

  @protected
  ResumePoint sse_decode_resume_point(SseDeserializer deserializer);

  @protected
  ResumeQueue sse_decode_resume_queue(SseDeserializer deserializer);

  @protected
  ScanMode sse_decode_scan_mode(SseDeserializer deserializer);

  @protected
  ScanSummary sse_decode_scan_summary(SseDeserializer deserializer);

  @protected
  SortKey sse_decode_sort_key(SseDeserializer deserializer);

  @protected
  Stats sse_decode_stats(SseDeserializer deserializer);

  @protected
  Track sse_decode_track(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album(Album self, SseSerializer serializer);

  @protected
  void sse_encode_artist(Artist self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cover_data(
    CoverData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lyrics(Lyrics self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_resume_point(
    ResumePoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resume_queue(
    ResumeQueue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_cover_data(CoverData self, SseSerializer serializer);

  @protected
  void sse_encode_delete_summary(DeleteSummary self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_CastedPrimitive_i_64(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album(List<Album> self, SseSerializer serializer);

  @protected
  void sse_encode_list_artist(List<Artist> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lyric_line(
    List<LyricLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist(List<Playlist> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_queue_entry(
    List<QueueEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_queue_track(
    List<QueueTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_line(LyricLine self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics(Lyrics self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cover_data(
    CoverData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_lyrics(
    Lyrics? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_resume_point(
    ResumePoint? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_resume_queue(
    ResumeQueue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_player_snapshot(
    PlayerSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer);

  @protected
  void sse_encode_playlist(Playlist self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_file_format(
    PlaylistFileFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_import(
    PlaylistImport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_queue_entry(QueueEntry self, SseSerializer serializer);

  @protected
  void sse_encode_queue_track(QueueTrack self, SseSerializer serializer);

  @protected
  void sse_encode_repeat_mode(RepeatMode self, SseSerializer serializer);

  @protected
  void sse_encode_resume_point(ResumePoint self, SseSerializer serializer);

  @protected
  void sse_encode_resume_queue(ResumeQueue self, SseSerializer serializer);

  @protected
  void sse_encode_scan_mode(ScanMode self, SseSerializer serializer);

  @protected
  void sse_encode_scan_summary(ScanSummary self, SseSerializer serializer);

  @protected
  void sse_encode_sort_key(SortKey self, SseSerializer serializer);

  @protected
  void sse_encode_stats(Stats self, SseSerializer serializer);

  @protected
  void sse_encode_track(Track self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
