// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 核心库版本号。Dart 侧调用它即可确认 FFI 通道已经打通。
String coreVersion() => RustLib.instance.api.crateApiAppCoreVersion();

/// 默认纳入曲库的音频扩展名（小写、不含点号），供 Dart 侧做兜底过滤。
List<String> defaultAudioExtensions() =>
    RustLib.instance.api.crateApiAppDefaultAudioExtensions();
