// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `track_or_none`, `with_db`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SortOrder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// 一首歌的封面：内嵌图优先，其次同目录的 `cover.jpg` / `folder.jpg` 等约定文件名
/// （判断规则都在 core 的 `metadata::read_cover` 里）。
///
/// 曲库没打开、id 不存在、没有封面、文件读不出来——统统返回 `None`：
/// 界面上退化成一张占位图就够了，不该因为一张图让播放界面报错。
Future<CoverData?> trackCover({required int trackId}) =>
    RustLib.instance.api.crateApiLibraryTrackCover(trackId: trackId);

/// Android 上常见的音乐目录，**只返回真实存在的那些**，UI 可直接拿来当扫描根。
///
/// 目录给的是真实路径而不是 SAF 的 `content://`：核心的扫描器基于 `std::fs`，
/// 需要能以普通文件方式打开这些文件（配合“所有文件访问”权限）。
List<String> suggestScanRoots() =>
    RustLib.instance.api.crateApiLibrarySuggestScanRoots();

/// 打开（不存在则创建）索引数据库。App 启动时调用一次。
///
/// 数据库应放在应用私有目录（Dart 侧用 `path_provider` 取），避免被其它应用改动。
void openLibrary({required String dbPath}) =>
    RustLib.instance.api.crateApiLibraryOpenLibrary(dbPath: dbPath);

/// 扫描一组根目录并写入索引；返回本次的新增 / 更新 / 删除 / 跳过统计。
///
/// `mode = incremental` 只重新解析 `(size, mtime)` 变化的文件，启动时首选。
/// 扫描是长任务，故保持异步：Dart 侧拿到的是 `Future`，不阻塞 UI 线程。
Future<ScanSummary> scanLibrary({
  required List<String> roots,
  required ScanMode mode,
}) => RustLib.instance.api.crateApiLibraryScanLibrary(roots: roots, mode: mode);

/// 列出曲库里的歌曲。`limit = None` 表示不限条数。
List<Track> listTracks({
  required SortKey sort,
  required bool descending,
  int? limit,
}) => RustLib.instance.api.crateApiLibraryListTracks(
  sort: sort,
  descending: descending,
  limit: limit,
);

/// 模糊搜索标题 / 艺术家 / 专辑。
List<Track> searchTracks({required String query, required int limit}) => RustLib
    .instance
    .api
    .crateApiLibrarySearchTracks(query: query, limit: limit);

/// 专辑聚合列表。
List<Album> listAlbums() => RustLib.instance.api.crateApiLibraryListAlbums();

/// 艺术家聚合列表。
List<Artist> listArtists() => RustLib.instance.api.crateApiLibraryListArtists();

/// 曲库统计（歌曲数 / 专辑数 / 总时长等）。
Stats libraryStats() => RustLib.instance.api.crateApiLibraryLibraryStats();

/// 所有播放列表（按名字排序）。
List<Playlist> playlists() => RustLib.instance.api.crateApiLibraryPlaylists();

/// 新建播放列表，返回它的 id。空名字由核心兜底成“新建列表”。
int createPlaylist({required String name}) =>
    RustLib.instance.api.crateApiLibraryCreatePlaylist(name: name);

/// 改名。界面负责拦住空名字：核心只会 trim，不会拒绝空串。
void renamePlaylist({required int playlistId, required String name}) => RustLib
    .instance
    .api
    .crateApiLibraryRenamePlaylist(playlistId: playlistId, name: name);

/// 删除播放列表。里面的条目一起没了，曲目本身不动。
void deletePlaylist({required int playlistId}) =>
    RustLib.instance.api.crateApiLibraryDeletePlaylist(playlistId: playlistId);

/// 把一首歌追加到列表末尾。已经在列表里时返回 `false`（同一列表不重复）。
bool addToPlaylist({required int playlistId, required int trackId}) => RustLib
    .instance
    .api
    .crateApiLibraryAddToPlaylist(playlistId: playlistId, trackId: trackId);

/// 从列表里移除一首歌，返回是否真的删掉了。
///
/// 收的是**曲目 id** 而不是下标：下标（position）会在曲目被重扫移除后留下空洞，
/// 界面按行删的是“这一行那一首歌”。
bool removeFromPlaylist({required int playlistId, required int trackId}) =>
    RustLib.instance.api.crateApiLibraryRemoveFromPlaylist(
      playlistId: playlistId,
      trackId: trackId,
    );

/// 列表里的曲目，按用户排的顺序返回。
List<Track> playlistTracks({required int playlistId}) =>
    RustLib.instance.api.crateApiLibraryPlaylistTracks(playlistId: playlistId);

/// [`musicplayer_core::Album`] 的镜像。
class Album {
  final String name;
  final String albumArtist;
  final int trackCount;
  final int durationMs;
  final int? year;
  final bool hasCover;

  const Album({
    required this.name,
    required this.albumArtist,
    required this.trackCount,
    required this.durationMs,
    this.year,
    required this.hasCover,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      albumArtist.hashCode ^
      trackCount.hashCode ^
      durationMs.hashCode ^
      year.hashCode ^
      hasCover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Album &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          albumArtist == other.albumArtist &&
          trackCount == other.trackCount &&
          durationMs == other.durationMs &&
          year == other.year &&
          hasCover == other.hasCover;
}

/// [`musicplayer_core::Artist`] 的镜像。
class Artist {
  final String name;
  final int trackCount;
  final int albumCount;

  const Artist({
    required this.name,
    required this.trackCount,
    required this.albumCount,
  });

  @override
  int get hashCode => name.hashCode ^ trackCount.hashCode ^ albumCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Artist &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          trackCount == other.trackCount &&
          albumCount == other.albumCount;
}

/// 封面图：Dart 侧直接把它喂给 `Image.memory`，所以只带 mime 与原始字节。
class CoverData {
  final String mime;
  final Uint8List data;

  const CoverData({required this.mime, required this.data});

  @override
  int get hashCode => mime.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverData &&
          runtimeType == other.runtimeType &&
          mime == other.mime &&
          data == other.data;
}

/// [`musicplayer_core::Playlist`] 的镜像。
class Playlist {
  final int id;
  final String name;
  final int trackCount;
  final int createdAt;

  const Playlist({
    required this.id,
    required this.name,
    required this.trackCount,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ trackCount.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Playlist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          trackCount == other.trackCount &&
          createdAt == other.createdAt;
}

/// [`musicplayer_core::ScanMode`] 的镜像。
enum ScanMode { full, incremental }

/// [`musicplayer_core::ScanSummary`] 的镜像。
class ScanSummary {
  final int added;
  final int updated;
  final int removed;
  final int skipped;
  final int failed;
  final int elapsedMs;
  final List<String> errors;

  const ScanSummary({
    required this.added,
    required this.updated,
    required this.removed,
    required this.skipped,
    required this.failed,
    required this.elapsedMs,
    required this.errors,
  });

  @override
  int get hashCode =>
      added.hashCode ^
      updated.hashCode ^
      removed.hashCode ^
      skipped.hashCode ^
      failed.hashCode ^
      elapsedMs.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanSummary &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          updated == other.updated &&
          removed == other.removed &&
          skipped == other.skipped &&
          failed == other.failed &&
          elapsedMs == other.elapsedMs &&
          errors == other.errors;
}

/// [`musicplayer_core::SortKey`] 的镜像。
enum SortKey { title, artist, album, addedAt, duration, path }

/// [`musicplayer_core::Stats`] 的镜像。
class Stats {
  final int trackCount;
  final int albumCount;
  final int artistCount;
  final int playlistCount;
  final int totalDurationMs;
  final int totalSizeBytes;

  const Stats({
    required this.trackCount,
    required this.albumCount,
    required this.artistCount,
    required this.playlistCount,
    required this.totalDurationMs,
    required this.totalSizeBytes,
  });

  @override
  int get hashCode =>
      trackCount.hashCode ^
      albumCount.hashCode ^
      artistCount.hashCode ^
      playlistCount.hashCode ^
      totalDurationMs.hashCode ^
      totalSizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Stats &&
          runtimeType == other.runtimeType &&
          trackCount == other.trackCount &&
          albumCount == other.albumCount &&
          artistCount == other.artistCount &&
          playlistCount == other.playlistCount &&
          totalDurationMs == other.totalDurationMs &&
          totalSizeBytes == other.totalSizeBytes;
}

/// [`musicplayer_core::Track`] 的镜像。
class Track {
  final int id;
  final String path;
  final String title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final String? genre;
  final int? year;
  final int? trackNo;
  final int? discNo;
  final int durationMs;
  final int? bitrate;
  final int? sampleRate;
  final int? channels;
  final int sizeBytes;
  final int modifiedAt;
  final bool hasCover;
  final int addedAt;

  const Track({
    required this.id,
    required this.path,
    required this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.genre,
    this.year,
    this.trackNo,
    this.discNo,
    required this.durationMs,
    this.bitrate,
    this.sampleRate,
    this.channels,
    required this.sizeBytes,
    required this.modifiedAt,
    required this.hasCover,
    required this.addedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      genre.hashCode ^
      year.hashCode ^
      trackNo.hashCode ^
      discNo.hashCode ^
      durationMs.hashCode ^
      bitrate.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      sizeBytes.hashCode ^
      modifiedAt.hashCode ^
      hasCover.hashCode ^
      addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          genre == other.genre &&
          year == other.year &&
          trackNo == other.trackNo &&
          discNo == other.discNo &&
          durationMs == other.durationMs &&
          bitrate == other.bitrate &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          sizeBytes == other.sizeBytes &&
          modifiedAt == other.modifiedAt &&
          hasCover == other.hasCover &&
          addedAt == other.addedAt;
}
