// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`, `snapshot_or_none`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 打开音频设备并启动播放线程。App 启动时调用一次，重复调用是安全的。
void openPlayer() => RustLib.instance.api.crateApiPlayerOpenPlayer();

/// 替换播放队列。`start_at` 是起始下标，`autoplay` 决定是否立刻开始播放。
void setPlayQueue({
  required List<QueueEntry> entries,
  required int startAt,
  required bool autoplay,
}) => RustLib.instance.api.crateApiPlayerSetPlayQueue(
  entries: entries,
  startAt: startAt,
  autoplay: autoplay,
);

void playerPlay() => RustLib.instance.api.crateApiPlayerPlayerPlay();

void playerPause() => RustLib.instance.api.crateApiPlayerPlayerPause();

/// 播放 / 暂停切换（界面上那个大按钮）。
void playerToggle() => RustLib.instance.api.crateApiPlayerPlayerToggle();

void playerStop() => RustLib.instance.api.crateApiPlayerPlayerStop();

void playerNext() => RustLib.instance.api.crateApiPlayerPlayerNext();

void playerPrevious() => RustLib.instance.api.crateApiPlayerPlayerPrevious();

void playerSeek({required int positionMs}) =>
    RustLib.instance.api.crateApiPlayerPlayerSeek(positionMs: positionMs);

/// 把队列当前项装进引擎并定位到 `position_ms`，但**先不出声**。
///
/// 「继续播放」用：启动时先 `set_play_queue` 入队再调它，底部播放条就能显示
/// 上次那首与进度；用户点一下播放才从那儿接着响。
void playerLoad({required int positionMs}) =>
    RustLib.instance.api.crateApiPlayerPlayerLoad(positionMs: positionMs);

void playerSetRepeat({required RepeatMode mode}) =>
    RustLib.instance.api.crateApiPlayerPlayerSetRepeat(mode: mode);

/// 打开 / 关闭随机播放。与循环模式相互独立：随机决定「下一首是谁」，
/// 循环决定「一轮放完怎么办」。
void playerSetShuffle({required bool shuffle}) =>
    RustLib.instance.api.crateApiPlayerPlayerSetShuffle(shuffle: shuffle);

/// 读取播放状态快照。UI 定时调用它刷新进度与状态。
PlayerSnapshot playerSnapshot() =>
    RustLib.instance.api.crateApiPlayerPlayerSnapshot();

/// [`musicplayer_audio::PlayerSnapshot`] 的镜像。
class PlayerSnapshot {
  final PlayerState state;
  final int positionMs;
  final int index;
  final int queueLen;
  final int trackId;

  /// 解码器从容器里算出来的总时长（毫秒）；曲库那份为 0 时 UI 用它兜底。
  final int durationMs;
  final RepeatMode repeat;
  final bool shuffle;
  final String? error;

  const PlayerSnapshot({
    required this.state,
    required this.positionMs,
    required this.index,
    required this.queueLen,
    required this.trackId,
    required this.durationMs,
    required this.repeat,
    required this.shuffle,
    this.error,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      positionMs.hashCode ^
      index.hashCode ^
      queueLen.hashCode ^
      trackId.hashCode ^
      durationMs.hashCode ^
      repeat.hashCode ^
      shuffle.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerSnapshot &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          positionMs == other.positionMs &&
          index == other.index &&
          queueLen == other.queueLen &&
          trackId == other.trackId &&
          durationMs == other.durationMs &&
          repeat == other.repeat &&
          shuffle == other.shuffle &&
          error == other.error;
}

/// [`musicplayer_audio::PlayerState`] 的镜像。
enum PlayerState { stopped, playing, paused, failed }

/// 队列项：Dart 侧用曲库里的 id + 绝对路径构造。
class QueueEntry {
  final int id;
  final String path;

  const QueueEntry({required this.id, required this.path});

  @override
  int get hashCode => id.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueueEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path;
}

/// [`musicplayer_audio::RepeatMode`] 的镜像。
enum RepeatMode { off, all, one }
