// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_track`, `run`

/// 引擎当前状态；引擎没起来时按“已停止”处理（通知栏据此收掉自己）。
Future<int> stateCode() =>
    RustLib.instance.api.crateApiPlaybackBridgeStateCode();

/// 当前位置（毫秒）。引擎没起来时返回 0。
Future<int> positionMs() =>
    RustLib.instance.api.crateApiPlaybackBridgePositionMs();

/// 当前曲目 id；`0` 表示没有播放项。
Future<int> trackId() => RustLib.instance.api.crateApiPlaybackBridgeTrackId();

/// 当前曲目标题（按 id 查曲库）；查不到返回空串。
Future<String> trackTitle() =>
    RustLib.instance.api.crateApiPlaybackBridgeTrackTitle();

/// 当前曲目的艺术家；没有标签时返回空串。
Future<String> trackArtist() =>
    RustLib.instance.api.crateApiPlaybackBridgeTrackArtist();

/// 当前曲目时长（毫秒）；查不到返回 0（通知栏据此不显示进度）。
Future<int> trackDurationMs() =>
    RustLib.instance.api.crateApiPlaybackBridgeTrackDurationMs();

/// 引擎是否已经初始化。App 还没走到 `open_player` 时，通知栏不该显示任何东西。
Future<bool> engineReady() =>
    RustLib.instance.api.crateApiPlaybackBridgeEngineReady();

/// 播放中的曲目播放失败的原因（给通知栏显示“播不了：…”）；没有则返回空串。
Future<String> errorText() =>
    RustLib.instance.api.crateApiPlaybackBridgeErrorText();

Future<bool> play() => RustLib.instance.api.crateApiPlaybackBridgePlay();

Future<bool> pause() => RustLib.instance.api.crateApiPlaybackBridgePause();

Future<bool> toggle() => RustLib.instance.api.crateApiPlaybackBridgeToggle();

Future<bool> next() => RustLib.instance.api.crateApiPlaybackBridgeNext();

Future<bool> previous() =>
    RustLib.instance.api.crateApiPlaybackBridgePrevious();

/// 跳转（毫秒）。负值按 0 处理——JNI 那边拿到的是 Kotlin 的 `Long`。
Future<bool> seekTo({required int positionMs}) =>
    RustLib.instance.api.crateApiPlaybackBridgeSeekTo(positionMs: positionMs);

/// 停止播放（通知栏上的“停止”/服务退出时用）。
Future<bool> stop() => RustLib.instance.api.crateApiPlaybackBridgeStop();
